import '../config/load-env.js';
import { db, closeDb } from '../db/client.js';
import { users, refreshTokens } from '../db/schema.js';
import { signAccessToken, signRefreshToken, hashToken, refreshTokenExpiresAt } from '../lib/jwt.js';
import { eq } from 'drizzle-orm';
const [u] = await db.select().from(users).where(eq(users.username, 'psantos26')).limit(1);
const a = await signAccessToken({ sub: u.id });
const r = await signRefreshToken({ sub: u.id });
await db.insert(refreshTokens).values({ userId: u.id, tokenHash: hashToken(r), deviceName: 'depuracion-claude', ipAddress: null, expiresAt: refreshTokenExpiresAt() });
console.log(JSON.stringify({ a, r }));
await closeDb();
