"""Generate worker.js with embedded base64 logo."""
import base64, pathlib

logo_path = pathlib.Path(__file__).parent.parent / 'public' / 'logo-final-titulo-sinFondo.png'
b64 = base64.b64encode(logo_path.read_bytes()).decode('ascii')

html = (
    '<!DOCTYPE html>\n'
    '<html lang="es">\n'
    '<head>\n'
    '  <meta charset="UTF-8" />\n'
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
    '  <title>The Show Verse</title>\n'
    '  <style>\n'
    '    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n'
    '    html, body {\n'
    '      height: 100%;\n'
    '      background: #000;\n'
    '      display: flex;\n'
    '      align-items: center;\n'
    '      justify-content: center;\n'
    '      font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', sans-serif;\n'
    '    }\n'
    '    .container {\n'
    '      display: flex;\n'
    '      flex-direction: column;\n'
    '      align-items: center;\n'
    '      gap: 2.5rem;\n'
    '      padding: 2rem;\n'
    '      text-align: center;\n'
    '    }\n'
    '    .logo {\n'
    '      width: min(480px, 85vw);\n'
    '      height: auto;\n'
    '      filter: drop-shadow(0 0 40px rgba(212,175,55,0.25));\n'
    '      animation: pulse 3s ease-in-out infinite;\n'
    '    }\n'
    '    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.7; } }\n'
    '    .divider {\n'
    '      width: 60px;\n'
    '      height: 1px;\n'
    '      background: linear-gradient(90deg, transparent, rgba(212,175,55,0.6), transparent);\n'
    '    }\n'
    '    .message {\n'
    '      color: rgba(255,255,255,0.45);\n'
    '      font-size: 0.95rem;\n'
    '      letter-spacing: 0.08em;\n'
    '      font-weight: 400;\n'
    '    }\n'
    '    .dot {\n'
    '      display: inline-block;\n'
    '      width: 5px; height: 5px;\n'
    '      background: rgba(212,175,55,0.5);\n'
    '      border-radius: 50%;\n'
    '      margin: 0 4px;\n'
    '      animation: blink 1.4s ease-in-out infinite;\n'
    '    }\n'
    '    .dot:nth-child(2) { animation-delay: 0.2s; }\n'
    '    .dot:nth-child(3) { animation-delay: 0.4s; }\n'
    '    @keyframes blink { 0%, 80%, 100% { opacity: 0.2; } 40% { opacity: 1; } }\n'
    '  </style>\n'
    '</head>\n'
    '<body>\n'
    '  <div class="container">\n'
    f'    <img class="logo" src="data:image/png;base64,{b64}" alt="The Show Verse" />\n'
    '    <div class="divider"></div>\n'
    '    <p class="message">\n'
    '      Servidor en mantenimiento\n'
    '      <span class="dot"></span><span class="dot"></span><span class="dot"></span>\n'
    '    </p>\n'
    '  </div>\n'
    '</body>\n'
    '</html>'
)

# Escape characters that would break a JS template literal
html_escaped = html.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

worker = (
    'export default {\n'
    '  async fetch(request, env, ctx) {\n'
    '    try {\n'
    '      const response = await fetch(request);\n'
    '      if (response.status >= 500) {\n'
    '        return serveMaintenancePage();\n'
    '      }\n'
    '      return response;\n'
    '    } catch (_err) {\n'
    '      return serveMaintenancePage();\n'
    '    }\n'
    '  },\n'
    '};\n'
    '\n'
    'function serveMaintenancePage() {\n'
    '  return new Response(MAINTENANCE_HTML, {\n'
    '    status: 503,\n'
    '    headers: {\n'
    "      'Content-Type': 'text/html; charset=utf-8',\n"
    "      'Cache-Control': 'no-store',\n"
    "      'Retry-After': '60',\n"
    '    },\n'
    '  });\n'
    '}\n'
    '\n'
    'const MAINTENANCE_HTML = `' + html_escaped + '`;\n'
)

out = pathlib.Path(__file__).parent / 'worker.js'
out.write_text(worker, encoding='utf-8')
print(f'worker.js written: {out.stat().st_size // 1024} KB')
